export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_TOTALPRICES = "UPDATE_TOTALPRICES";
export const CLEAR_CART = "CLEAR_CART";
export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";
